name: learn-github-actions
on: 
  pull_request:

jobs:
  check-ci-version:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          echo "${{github.ref}}"
          